### ISSUE TITLE
Error in FUN(X[[i]], ...) : object 'pos' not found in showDigitizedImage()

### ISSUE THREAD

**Issue by Otoliths** [droglenc/RFishBC#12]
> library(RFishBC)
> #Measure Radii
> digitizeRadii("Oto.jpg",
+               id = "Oto",
+               reading = "DHO",
+               description = "Used to demonstrate use of scale-bar.",
+               scaleBar = TRUE,
+               scaleBarLength = 0.1,# this image had a 1-mm scale-bar
+               edgeIsAnnulus = F)
✔ Loaded the Oto.jpg image.

☰ Select the endpoints of the scale-bar.
     Press 'f' when finished, 'd' to delete selection.
✔ Found scaling factor from the selected scale-bar.

☰ Select the FOCUS (center) and MARGIN (edge) of the structure.
     Press 'f' when finished, 'd' to delete selection.
✔ Transect selected and shown on image.

☰ Select points that are annuli.
     Press 'f' when finished, 'd' to delete selection.
✔ 6 points were selected.

✔ Results written to Oto_DHO.rds

> #Data from One Structure
> combineData("Oto_DHO.rds")
   id reading agecap ann        rad    radcap
1 Oto     DHO      4   1 0.05653221 0.2061728
2 Oto     DHO      4   2 0.10065765 0.2061728
3 Oto     DHO      4   3 0.13284496 0.2061728
4 Oto     DHO      4   4 0.16040859 0.2061728
> combineData("Oto_DHO.rds",outFormat = "wide")
   id reading agecap    radcap       rad1      rad2     rad3      rad4
1 Oto     DHO      4 0.2061728 0.05653221 0.1006576 0.132845 0.1604086
> #Visualize One Set of Annuli
> showDigitizedImage("Oto_DHO.rds",
+                    pch.show = "+",
+                    col.show = "blue",
+                    col.transect = "white",
+                    col.ann = "black",
+                    cex.ann = 1,
+                    annuliLabels = 1:4,
+                    lwd.transect = 2)
Error in FUN(X[[i]], ...) : object 'pos' not found

**Comment by droglenc** [comment]
Can you please send me your Oto.jpg file and also the Oto_DHO.rds file saved in the same directory? I will see if I can troubleshoot from there. Please send to derek [at] derekogle.com.

**Comment by droglenc** [comment]
This was a bug in how I found the position of the labels relative to the points. This is addressed in the development version and will be in v0.0.10 when released.

Thank you for bringing this error to my attention.
