### ISSUE TITLE
Unexpected results from BC

### ISSUE THREAD

**Issue by adospace** [droglenc/RFishBC#46]
**Describe the bug**
Seems that results from BC are exactly backward

**To Reproduce**
Please run this script:
```
> 
> library(RFishBC)   # for bcFuns()
> library(FSA)       # for validn(), sumTable()
> library(dplyr)     # for %>%, inner_join(), arrange(), group_by, summarize()
> library(RJSONIO)
> 
> fishRadii <- read.csv("FishRadii.csv",stringsAsFactors=FALSE) %>% mutate(id=as.character(id))
> head(fishRadii)
  id reading agecap    radcap       rad1      rad2      rad3      rad4
1  1     HBO      4 0.4381053 0.12743160 0.2650279 0.3268283 0.3867132
2  2     HBO      2 0.5887905 0.17663490 0.3529062 0.5887905        NA
3  3     HBO      4 0.3104990 0.09473057 0.1743012 0.2300987 0.2707363
4  4     HBO      6 0.3049929 0.07608640 0.1324872 0.1847441 0.2236615
5  5     HBO      2 0.3128672 0.13736670 0.2303700 0.3128672        NA
6  6     HBO      2 0.2783109 0.09896087 0.1955856 0.2783109        NA
       rad5      rad6      rad7
1 0.4381053        NA        NA
2        NA        NA        NA
3 0.3104990        NA        NA
4 0.2562328 0.2829117 0.3049929
5        NA        NA        NA
6        NA        NA        NA
> 
> fishData <- read.csv("FishData.csv",stringsAsFactors=FALSE) %>% mutate(id=as.character(id))
> head(fishData)
  id species  lake           gear yearcap lencap
1  1     BLG VIK69 Electrofishing    2020    171
2  2     BLG VIK69 Electrofishing    2020    120
3  3     BLG VIK69 Electrofishing    2020    172
4  4     BLG VIK69 Electrofishing    2020    196
5  5     BLG VIK69 Electrofishing    2020    110
6  6     BLG VIK69 Electrofishing    2020    145
> 
> data <- inner_join(fishRadii,fishData,by="id")
> 
> result <- backCalc(data,lencap,BCM="FRALE",inFormat="wide",digits=0)
✔ Using the Fraser-Lee model with a=214.25871707143.
> 
> head(result)
  id reading agecap species  lake           gear yearcap lencap len1 len2 len3
1  1     HBO      4     BLG VIK69 Electrofishing    2020    171  202  188  182
2 10     HBO      2     BLG VIK69 Electrofishing    2020    118  175  147   NA
3 11     HBO      6     BLG VIK69 Electrofishing    2020    182  206  199  195
4 12     HBO      3     BLG VIK69 Electrofishing    2020    141  196  187  170
5 13     HBO      4     BLG VIK69 Electrofishing    2020    172  202  190  182
6 14     HBO      4     BLG VIK69 Electrofishing    2020    175  199  191  184
  len4 len5 len6
1  176   NA   NA
2   NA   NA   NA
3  191  188  185
4   NA   NA   NA
5  177   NA   NA
6  179   NA   NA
```

**Expected behavior**
I'm expecting that calculated length get larger when age increase. Take for example fish at id=1, len at capture is 171, radiis are 0.12743160 0.2650279 0.3268283 0.3867132 lengths should go from a lower value of 171 to exactly 171 but instead this is returned:
202  188  182 176 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - R Version 4.0.3

Am I missing something when generating the BC lengths? do you have any hint?

Thank you very much!

PS: I've attached the files required to run the script as a zip file
[BC_Bug_Repro_Sample.zip](https://github.com/droglenc/RFishBC/files/5841445/BC_Bug_Repro_Sample.zip)

**Comment by droglenc** [comment]
Sorry for the quick reply (I am headed out in a few minutes) ... I can look at this more later if need be ... but I think the issue may be with "a" ... see

```
✔ Using the Fraser-Lee model with a=214.25871707143.
```

As this "correction factor" is greater than the fish's TL, that is going to cause problems. This implies some sort of issue with the regression of `lencap` on `radcap`. A couple of quick diagnostic thoughts.

First, what does the plot of `lencap` on `radcap` look like ... try `plot(lencap~radcap,data=data)`. It should be linear, increasing, and relatively tight.

Second, what happens if you set `a=` in `backCalc()`? So something like (as a test) ...

```
result <- backCalc(data,lencap,BCM="FRALE",inFormat="wide",digits=0,a=25)
```

Do these results look as you expected?

**Comment by adospace** [comment]
Thanks for the prompt reply, it definitively pointed us in the right direction: using a=25 parameter I get much more reasonable values.
```
> result <- backCalc(data,lencap,BCM="FRALE",inFormat="wide",digits=0,a=0.25)
✔ Using the Fraser-Lee model with a=0.25.
> 
> head(result)
  id reading agecap species  lake           gear yearcap lencap len1 len2 len3
1  1     HBO      4     BLG VIK69 Electrofishing    2020    171   50  104  128
2 10     HBO      2     BLG VIK69 Electrofishing    2020    118   48   82   NA
3 11     HBO      6     BLG VIK69 Electrofishing    2020    182   49   85  109
4 12     HBO      3     BLG VIK69 Electrofishing    2020    141   35   53   85
5 13     HBO      4     BLG VIK69 Electrofishing    2020    172   51   97  130
6 14     HBO      4     BLG VIK69 Electrofishing    2020    175   70  104  133
  len4 len5 len6
1  151   NA   NA
2   NA   NA   NA
3  133  150  167
4   NA   NA   NA
5  153   NA   NA
6  156   NA   NA
```
Plotting the lencap vs radcap I instead get this:
![image](https://user-images.githubusercontent.com/10573253/105187280-e5649a00-5b32-11eb-8ecd-cca42cb2779f.png)

that I guess would explain why the auto-calculated "a" value is so high.

**Comment by droglenc** [comment]
I think that this means that `backCalc()` is working correctly ... it is just that the auto-calculated `a=` is poor due to the odd relationship between length and radius at capture. Are these real data?

Note that I started a new issue (#47) to send a warning about  bad `a=` values.

**Comment by adospace** [comment]
Yes are real data, maybe there is a problem with the radii collect stage that requires more investigation on our side. I agree with you that baclCalc() has no issue so I'm going to close this ticket.
Thank you for your support.
